export const HEDGE_FUNDS = [
  { rank:1, name:'Bridgewater Associates', manager:'Ray Dalio', country:'USA', aum:124, strategy:'Global Macro', annualReturn:8.2, founded:1975 },
  { rank:2, name:'Man Group', manager:'Robyn Grew', country:'UK', aum:72, strategy:'Multi-Strategy', annualReturn:11.4, founded:1783 },
  { rank:3, name:'Renaissance Technologies', manager:'Peter Brown', country:'USA', aum:57, strategy:'Quantitative', annualReturn:31.5, founded:1982 },
  { rank:4, name:'Millennium Management', manager:'Israel Englander', country:'USA', aum:55, strategy:'Multi-Strategy', annualReturn:13.1, founded:1989 },
  { rank:5, name:'Citadel', manager:'Ken Griffin', country:'USA', aum:53, strategy:'Multi-Strategy', annualReturn:15.3, founded:1990 },
  { rank:6, name:'Two Sigma', manager:'John Overdeck', country:'USA', aum:46, strategy:'Quantitative', annualReturn:10.9, founded:2001 },
  { rank:7, name:'Farallon Capital', manager:'Thomas Steyer', country:'USA', aum:39, strategy:'Multi-Strategy', annualReturn:9.7, founded:1986 },
  { rank:8, name:'Tiger Global', manager:'Chase Coleman', country:'USA', aum:35, strategy:'Long/Short Equity', annualReturn:14.6, founded:2001 },
  { rank:9, name:'Elliott Management', manager:'Paul Singer', country:'USA', aum:34, strategy:'Event Driven', annualReturn:12.3, founded:1977 },
  { rank:10, name:'Baupost Group', manager:'Seth Klarman', country:'USA', aum:32, strategy:'Value', annualReturn:10.1, founded:1982 },
  { rank:11, name:'Marshall Wace', manager:'Paul Marshall', country:'UK', aum:31, strategy:'Long/Short Equity', annualReturn:13.5, founded:1997 },
  { rank:12, name:'Soros Fund Management', manager:'George Soros', country:'USA', aum:25, strategy:'Global Macro', annualReturn:20.0, founded:1970 },
  { rank:13, name:'Pershing Square', manager:'Bill Ackman', country:'USA', aum:26, strategy:'Activist', annualReturn:16.4, founded:2004 },
  { rank:14, name:'Appaloosa Management', manager:'David Tepper', country:'USA', aum:25, strategy:'Event Driven', annualReturn:14.9, founded:1993 },
  { rank:15, name:'Point72', manager:'Steve Cohen', country:'USA', aum:21, strategy:'Multi-Strategy', annualReturn:11.8, founded:2014 },
  { rank:16, name:'Brevan Howard', manager:'Alan Howard', country:'UK', aum:18, strategy:'Global Macro', annualReturn:10.6, founded:2002 },
  { rank:17, name:'Rokos Capital', manager:'Chris Rokos', country:'UK', aum:15, strategy:'Global Macro', annualReturn:18.5, founded:2015 },
  { rank:18, name:'Balyasny Asset Management', manager:'Dmitry Balyasny', country:'USA', aum:16, strategy:'Multi-Strategy', annualReturn:12.6, founded:2001 },
  { rank:19, name:'Coatue Management', manager:'Philippe Laffont', country:'USA', aum:20, strategy:'Long/Short Equity', annualReturn:18.3, founded:1999 },
  { rank:20, name:'AQR Capital', manager:'Cliff Asness', country:'USA', aum:19, strategy:'Quantitative', annualReturn:9.4, founded:1998 },
  { rank:21, name:'Platinum Asset Management', manager:'Kerr Neilson', country:'Australia', aum:8, strategy:'Global', annualReturn:10.8, founded:1994 },
  { rank:22, name:'Regal Funds Management', manager:'Philip King', country:'Australia', aum:3, strategy:'Long/Short Equity', annualReturn:16.8, founded:2004 },
  { rank:23, name:'Citadel Australia', manager:'Ken Griffin', country:'Australia', aum:4, strategy:'Multi-Strategy', annualReturn:14.1, founded:2008 },
  { rank:24, name:'Bennelong Funds', manager:'John Burke', country:'Australia', aum:2, strategy:'Long/Short Equity', annualReturn:13.7, founded:2003 },
  { rank:25, name:'Caledonia Investments', manager:'Will Vicars', country:'Australia', aum:1, strategy:'Long/Short Equity', annualReturn:14.2, founded:1992 },
  { rank:26, name:'GIC Private Limited', manager:'Lim Chow Kiat', country:'Singapore', aum:690, strategy:'Sovereign Wealth', annualReturn:6.9, founded:1981 },
  { rank:27, name:'Segantii Capital', manager:'Simon Sadler', country:'Hong Kong', aum:3, strategy:'Event Driven', annualReturn:14.9, founded:2007 },
  { rank:28, name:'Hengde Asset Management', manager:'Zhang Lei', country:'China', aum:5, strategy:'Long/Short Equity', annualReturn:21.3, founded:2005 },
  { rank:29, name:'Partners Group', manager:'David Layton', country:'Switzerland', aum:10, strategy:'Private Equity', annualReturn:12.4, founded:1996 },
  { rank:30, name:'Greenoaks Capital', manager:'Neil Mehta', country:'USA', aum:9, strategy:'Long/Short Equity', annualReturn:22.1, founded:2012 },
];
