import { useState, useEffect, useRef } from "react";
export default function Watchlist() {
  const [lists, setLists] = useState(() => { try { const s = localStorage.getItem("vestry_watchlists"); return s ? JSON.parse(s) : []; } catch { return []; } });
  const [selMarket, setSelMarket] = useState(null);
  const [selSector, setSelSector] = useState(null);
  const [showAddMarket, setShowAddMarket] = useState(false);
  const [showAddSector, setShowAddSector] = useState(false);
  const [showAddStock, setShowAddStock] = useState(false);
  const [newMarketName, setNewMarketName] = useState("");
  const [newSectorName, setNewSectorName] = useState("");
  const [stockQuery, setStockQuery] = useState("");
  const [stockExchange, setStockExchange] = useState("US");
  const [stockResults, setStockResults] = useState([]);
  const [searching, setSearching] = useState(false);
  const [prices, setPrices] = useState({});
  const searchTimer = useRef(null);
  const C = { bg:"#0d0f14", surface:"#13161e", card:"#1a1e28", border:"#1e2335", text:"#e8ecf4", sub:"#7c87a0", green:"#10b981", red:"#ef4444", accent:"#6366f1" };
  const EXCHANGES = [{code:"US",label:"🇺🇸 USA"},{code:"ASX",label:"🇦🇺 Australia"},{code:"TSE",label:"🇯🇵 Japan"},{code:"LSE",label:"🇬🇧 UK"},{code:"HKG",label:"🇭🇰 Hong Kong"},{code:"TSX",label:"🇨🇦 Canada"},{code:"FRA",label:"🇩🇪 Germany"},{code:"EPA",label:"🇫🇷 France"},{code:"SGX",label:"🇸🇬 Singapore"},{code:"NZX",label:"🇳🇿 New Zealand"}];
  useEffect(() => { localStorage.setItem("vestry_watchlists", JSON.stringify(lists)); }, [lists]);
  const save = (u) => setLists(u);
  const addMarket = () => { if (!newMarketName.trim()) return; save([...lists, { id:Date.now(), name:newMarketName.trim(), sectors:[] }]); setNewMarketName(""); setShowAddMarket(false); };
  const deleteMarket = (id) => { save(lists.filter(m => m.id !== id)); if (selMarket?.id === id) { setSelMarket(null); setSelSector(null); } };
  const addSector = () => { if (!newSectorName.trim() || !selMarket) return; const u = lists.map(m => m.id === selMarket.id ? { ...m, sectors:[...m.sectors,{id:Date.now(),name:newSectorName.trim(),stocks:[]}] } : m); save(u); setNewSectorName(""); setShowAddSector(false); setSelMarket(u.find(m => m.id === selMarket.id)); };
  const deleteSector = (sid) => { const u = lists.map(m => m.id === selMarket.id ? { ...m, sectors:m.sectors.filter(s => s.id !== sid) } : m); save(u); setSelMarket(u.find(m => m.id === selMarket.id)); if (selSector?.id === sid) setSelSector(null); };
  const addStock = (stock) => { if (!selMarket || !selSector) return; const u = lists.map(m => m.id === selMarket.id ? { ...m, sectors:m.sectors.map(s => s.id === selSector.id ? { ...s, stocks:[...s.stocks.filter(x => x.ticker !== stock.ticker), stock] } : s) } : m); save(u); const um = u.find(m => m.id === selMarket.id); setSelMarket(um); setSelSector(um.sectors.find(s => s.id === selSector.id)); setShowAddStock(false); setStockQuery(""); setStockResults([]); };
  const removeStock = (ticker) => { const u = lists.map(m => m.id === selMarket.id ? { ...m, sectors:m.sectors.map(s => s.id === selSector.id ? { ...s, stocks:s.stocks.filter(x => x.ticker !== ticker) } : s) } : m); save(u); const um = u.find(m => m.id === selMarket.id); setSelMarket(um); setSelSector(um.sectors.find(s => s.id === selSector.id)); };
  const fetchPrice = async (ticker) => { try { if (ticker.endsWith(".AX")) { const r = await fetch("/api/asx-price?ticker=" + ticker); const d = await r.json(); return { c:d.c, pc:d.pc }; } else { const r = await fetch("https://finnhub.io/api/v1/quote?symbol=" + ticker + "&token=d0oOHQHr01qhcnk56bs0d0oOHQHr01qhcnk56bsg"); const d = await r.json(); return { c:d.c, pc:d.pc }; } } catch { return null; } };
  useEffect(() => { if (!selSector?.stocks?.length) return; const load = async () => { const res = {}; await Promise.all(selSector.stocks.map(async s => { const p = await fetchPrice(s.ticker); if (p) res[s.ticker] = p; })); setPrices(p => ({...p,...res})); }; load(); }, [selSector]);
  useEffect(() => { if (!stockQuery.trim()) { setStockResults([]); return; } clearTimeout(searchTimer.current); searchTimer.current = setTimeout(async () => { setSearching(true); try { const r = await fetch("https://finnhub.io/api/v1/search?q=" + encodeURIComponent(stockQuery) + "&exchange=&token=d0oOHQHr01qhcnk56bs0d0oOHQHr01qhcnk56bsg"); const d = await r.json(); let res = (d.result || []); const ex = stockExchange; if (ex==="ASX") res=res.filter(r=>r.symbol?.endsWith(".AX")); else if (ex==="TSE") res=res.filter(r=>r.symbol?.endsWith(".T")); else if (ex==="LSE") res=res.filter(r=>r.symbol?.endsWith(".L")); else if (ex==="HKG") res=res.filter(r=>r.symbol?.endsWith(".HK")); else if (ex==="TSX") res=res.filter(r=>r.symbol?.endsWith(".TO")); else if (ex==="FRA") res=res.filter(r=>r.symbol?.endsWith(".DE")); else if (ex==="EPA") res=res.filter(r=>r.symbol?.endsWith(".PA")); else res=res.filter(r=>r.type==="Common Stock"&&!r.symbol?.includes(".")); setStockResults(res.slice(0,6)); } catch {} setSearching(false); }, 400); }, [stockQuery, stockExchange]);
  const fmt = n => n != null ? "$" + Number(n).toFixed(2) : "--";
  const chg = (c,pc) => pc && c ? (((c-pc)/pc)*100).toFixed(2) : null;
  return (
    <div style={{padding:"0 0 40px"}}>
      {showAddMarket && <div onClick={()=>setShowAddMarket(false)} style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.7)",zIndex:1000,display:"flex",alignItems:"center",justifyContent:"center"}}><div onClick={e=>e.stopPropagation()} style={{background:C.card,border:"1px solid "+C.border,borderRadius:16,padding:28,width:380}}><div style={{fontWeight:700,fontSize:16,color:C.text,marginBottom:16}}>Add Market</div><input autoFocus value={newMarketName} onChange={e=>setNewMarketName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addMarket()} placeholder="e.g. Australia, Japan, USA..." style={{width:"100%",background:C.surface,border:"1px solid "+C.border,borderRadius:10,padding:"10px 14px",color:C.text,fontSize:14,outline:"none",marginBottom:16,boxSizing:"border-box"}}/><div style={{display:"flex",gap:10}}><button onClick={addMarket} style={{flex:1,background:C.accent,border:"none",borderRadius:10,color:"#fff",fontWeight:700,fontSize:14,padding:"10px 0",cursor:"pointer"}}>Add</button><button onClick={()=>setShowAddMarket(false)} style={{flex:1,background:C.surface,border:"1px solid "+C.border,borderRadius:10,color:C.sub,fontWeight:600,fontSize:14,padding:"10px 0",cursor:"pointer"}}>Cancel</button></div></div></div>}
      {showAddSector && <div onClick={()=>setShowAddSector(false)} style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.7)",zIndex:1000,display:"flex",alignItems:"center",justifyContent:"center"}}><div onClick={e=>e.stopPropagation()} style={{background:C.card,border:"1px solid "+C.border,borderRadius:16,padding:28,width:380}}><div style={{fontWeight:700,fontSize:16,color:C.text,marginBottom:16}}>Add Sector to {selMarket?.name}</div><input autoFocus value={newSectorName} onChange={e=>setNewSectorName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addSector()} placeholder="e.g. Mining, Technology, Banks..." style={{width:"100%",background:C.surface,border:"1px solid "+C.border,borderRadius:10,padding:"10px 14px",color:C.text,fontSize:14,outline:"none",marginBottom:16,boxSizing:"border-box"}}/><div style={{display:"flex",gap:10}}><button onClick={addSector} style={{flex:1,background:C.accent,border:"none",borderRadius:10,color:"#fff",fontWeight:700,fontSize:14,padding:"10px 0",cursor:"pointer"}}>Add</button><button onClick={()=>setShowAddSector(false)} style={{flex:1,background:C.surface,border:"1px solid "+C.border,borderRadius:10,color:C.sub,fontWeight:600,fontSize:14,padding:"10px 0",cursor:"pointer"}}>Cancel</button></div></div></div>}
      {showAddStock && <div onClick={()=>setShowAddStock(false)} style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.7)",zIndex:1000,display:"flex",alignItems:"center",justifyContent:"center"}}><div onClick={e=>e.stopPropagation()} style={{background:C.card,border:"1px solid "+C.border,borderRadius:16,padding:28,width:440,maxHeight:"80vh",overflowY:"auto"}}><div style={{fontWeight:700,fontSize:16,color:C.text,marginBottom:16}}>Add Stock to {selSector?.name}</div><div style={{display:"flex",gap:6,marginBottom:10,flexWrap:"wrap"}}>{EXCHANGES.map(ex=><button key={ex.code} onClick={()=>{setStockExchange(ex.code);setStockQuery("");setStockResults([]);}} style={{padding:"5px 10px",borderRadius:8,border:"none",cursor:"pointer",fontSize:12,fontWeight:600,background:stockExchange===ex.code?C.accent:C.surface,color:stockExchange===ex.code?"#fff":C.sub}}>{ex.label}</button>)}</div><input autoFocus value={stockQuery} onChange={e=>setStockQuery(e.target.value)} placeholder="Search ticker or company..." style={{width:"100%",background:C.surface,border:"1px solid "+C.border,borderRadius:10,padding:"10px 14px",color:C.text,fontSize:14,outline:"none",marginBottom:10,boxSizing:"border-box"}}/>{searching&&<div style={{color:C.sub,fontSize:13,marginBottom:8}}>Searching...</div>}{stockResults.map(r=><div key={r.symbol} onClick={()=>addStock({ticker:r.symbol,name:r.description,exchange:stockExchange})} style={{padding:"10px 14px",borderRadius:10,background:C.surface,border:"1px solid "+C.border,marginBottom:6,cursor:"pointer",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontWeight:700,fontSize:13,color:C.text}}>{r.symbol}</div><div style={{color:C.sub,fontSize:11}}>{r.description}</div></div><div style={{color:C.accent,fontSize:12}}>+ Add</div></div>)}<button onClick={()=>setShowAddStock(false)} style={{width:"100%",background:C.surface,border:"1px solid "+C.border,borderRadius:10,color:C.sub,fontWeight:600,fontSize:14,padding:"10px 0",cursor:"pointer",marginTop:6}}>Cancel</button></div></div>}
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}>
        <div><div style={{fontWeight:800,fontSize:20,color:C.text}}>Watchlists</div><div style={{color:C.sub,fontSize:13,marginTop:2}}>Track stocks across any market and sector</div></div>
        <button onClick={()=>setShowAddMarket(true)} style={{background:C.accent,border:"none",borderRadius:10,color:"#fff",fontWeight:700,fontSize:13,padding:"10px 18px",cursor:"pointer"}}>+ Add Market</button>
      </div>
      {lists.length===0&&<div style={{background:"#13161e",border:"1px solid #1e2335",borderRadius:14,padding:"60px 20px",textAlign:"center"}}><div style={{fontSize:40,marginBottom:12}}>📋</div><div style={{fontWeight:700,fontSize:16,color:"#e8ecf4",marginBottom:8}}>No watchlists yet</div><div style={{color:"#7c87a0",fontSize:13}}>Click + Add Market to get started</div></div>}
      <div style={{display:"grid",gridTemplateColumns:selMarket?(selSector?"200px 200px 1fr":"200px 1fr"):"1fr",gap:16}}>
        {lists.length>0&&<div style={{background:C.surface,border:"1px solid "+C.border,borderRadius:14,overflow:"hidden"}}><div style={{padding:"12px 16px",borderBottom:"1px solid "+C.border,fontWeight:700,fontSize:13,color:C.text}}>Markets</div>{lists.map(m=><div key={m.id} onClick={()=>{setSelMarket(m);setSelSector(null);}} style={{padding:"12px 16px",borderBottom:"1px solid "+C.border,cursor:"pointer",background:selMarket?.id===m.id?C.card:"transparent",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontWeight:600,fontSize:13,color:C.text}}>{m.name}</div><div style={{color:C.sub,fontSize:11}}>{m.sectors.length} sectors</div></div><button onClick={e=>{e.stopPropagation();deleteMarket(m.id);}} style={{background:"none",border:"none",color:C.sub,cursor:"pointer",fontSize:14,padding:"2px 6px"}}>✕</button></div>)}</div>}
        {selMarket&&<div style={{background:C.surface,border:"1px solid "+C.border,borderRadius:14,overflow:"hidden"}}><div style={{padding:"12px 16px",borderBottom:"1px solid "+C.border,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{fontWeight:700,fontSize:13,color:C.text}}>{selMarket.name} Sectors</div><button onClick={()=>setShowAddSector(true)} style={{background:C.accent,border:"none",borderRadius:8,color:"#fff",fontWeight:700,fontSize:11,padding:"4px 10px",cursor:"pointer"}}>+ Add</button></div>{selMarket.sectors.length===0&&<div style={{padding:"30px 16px",textAlign:"center",color:C.sub,fontSize:13}}>No sectors yet</div>}{selMarket.sectors.map(s=><div key={s.id} onClick={()=>setSelSector(s)} style={{padding:"12px 16px",borderBottom:"1px solid "+C.border,cursor:"pointer",background:selSector?.id===s.id?C.card:"transparent",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontWeight:600,fontSize:13,color:C.text}}>{s.name}</div><div style={{color:C.sub,fontSize:11}}>{s.stocks.length} stocks</div></div><button onClick={e=>{e.stopPropagation();deleteSector(s.id);}} style={{background:"none",border:"none",color:C.sub,cursor:"pointer",fontSize:14,padding:"2px 6px"}}>✕</button></div>)}</div>}
        {selSector&&<div style={{background:C.surface,border:"1px solid "+C.border,borderRadius:14,overflow:"hidden"}}><div style={{padding:"12px 16px",borderBottom:"1px solid "+C.border,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{fontWeight:700,fontSize:13,color:C.text}}>{selSector.name}</div><button onClick={()=>setShowAddStock(true)} style={{background:C.accent,border:"none",borderRadius:8,color:"#fff",fontWeight:700,fontSize:11,padding:"4px 10px",cursor:"pointer"}}>+ Add Stock</button></div>{selSector.stocks.length===0&&<div style={{padding:"30px 16px",textAlign:"center",color:C.sub,fontSize:13}}>No stocks yet — click + Add Stock</div>}<div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr auto",padding:"8px 16px",color:C.sub,fontSize:11,textTransform:"uppercase",letterSpacing:"0.06em",borderBottom:"1px solid "+C.border}}>{["Stock","Price","Change",""].map((h,i)=><span key={i} style={{textAlign:i>0?"right":"left"}}>{h}</span>)}</div>{selSector.stocks.map(stock=>{const p=prices[stock.ticker];const pct=p?chg(p.c,p.pc):null;const isUp=pct>0;return(<div key={stock.ticker} style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr auto",padding:"12px 16px",borderBottom:"1px solid "+C.border,alignItems:"center"}}><div><div style={{fontWeight:700,fontSize:13,color:C.text}}>{stock.ticker}</div><div style={{color:C.sub,fontSize:11}}>{stock.name?.slice(0,22)}</div></div><div style={{textAlign:"right",fontWeight:700,color:C.text}}>{fmt(p?.c)}</div><div style={{textAlign:"right",color:pct==null?C.sub:isUp?C.green:C.red,fontWeight:600}}>{pct!=null?(isUp?"+":"")+pct+"%":"--"}</div><button onClick={()=>removeStock(stock.ticker)} style={{background:"none",border:"none",color:C.sub,cursor:"pointer",fontSize:14,padding:"2px 8px"}}>✕</button></div>);})}</div>}
      </div>
    </div>
  );
}
